### PR TITLE
Hi

### PR DESCRIPTION
**Pull request by applqpak**
Blah.

### CODE REVIEW

**Comment by TheDragonRing** [comment]
Erm, thx but why all that stuff in Main.php I'm only setting -* permission to the player if it isn't OP/doesn't haven't a certain perm onJoin..... Lol it disables all commands currently

**Comment by applqpak** [comment]
Oh.

**Comment by TheDragonRing** [comment]
Actually nvm

**Comment by TheDragonRing** [comment]
This is good code for a feature I was planning to add in next update

**Comment by TheDragonRing** [comment]
Just reverse it to allow it if it's in the config and if it's not in config disallow it!

**Comment by applqpak** [comment]
What?

**Comment by applqpak** [comment]
Ah ok

**Comment by TheDragonRing** [comment]
Do you mind if I leave that to you for a few mins if you understood that while I go write up the LICENSE.md

**Comment by applqpak** [comment]
I already did it.

**Comment by TheDragonRing** [comment]
Oh ok

**Comment by TheDragonRing** [comment]
Thx lol

**Pull request merged**
